# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "bugs", :force => true do |t|
    t.column "user_id",     :integer,   :limit => 20,                  :null => false
    t.column "project_id",  :integer,   :limit => 20,                  :null => false
    t.column "title",       :string,    :limit => 500, :default => "", :null => false
    t.column "description", :text,                     :default => "", :null => false
    t.column "level",       :integer,   :limit => 1,                   :null => false
    t.column "status",      :integer,   :limit => 1,                   :null => false
    t.column "feedback",    :integer,   :limit => 1,                   :null => false
    t.column "created_on",  :datetime,                                 :null => false
    t.column "updated_on",  :timestamp,                                :null => false
  end

  create_table "companies", :force => true do |t|
    t.column "name",       :string,    :limit => 64, :default => "", :null => false
    t.column "created_on", :datetime,                                :null => false
    t.column "updated_on", :timestamp,                               :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "name",       :string,    :limit => 32, :default => "", :null => false
    t.column "status",     :integer,   :limit => 1,                  :null => false
    t.column "created_on", :datetime,                                :null => false
    t.column "updated_on", :timestamp,                               :null => false
  end

  create_table "projects_users", :id => false, :force => true do |t|
    t.column "user_id",    :integer, :limit => 20, :null => false
    t.column "project_id", :integer, :limit => 20, :null => false
  end

  create_table "settings", :id => false, :force => true do |t|
    t.column "open_reg",        :integer, :limit => 1, :null => false
    t.column "rpc_entry_get",   :integer, :limit => 1, :null => false
    t.column "rpc_entry_post",  :integer, :limit => 1, :null => false
    t.column "import_basecamp", :integer, :limit => 1, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "company_id",    :integer,  :limit => 20,                   :null => false
    t.column "user_type",     :integer,  :limit => 1
    t.column "user_name",     :string,   :limit => 64,   :default => ""
    t.column "first_name",    :string,   :limit => 128,  :default => ""
    t.column "last_name",     :string,   :limit => 128,  :default => ""
    t.column "email",         :string,   :limit => 128,  :default => ""
    t.column "phone",         :string,   :limit => 20,   :default => ""
    t.column "password",      :string,   :limit => 1024, :default => ""
    t.column "should_notify", :integer,  :limit => 1
    t.column "created_on",    :datetime,                                 :null => false
    t.column "updated_on",    :datetime,                                 :null => false
  end

end
